### ISSUE TITLE
Create exonomy@exosystems.net and exocracy@exosystems.net mailboxes

### ISSUE THREAD

**Issue by exonomyapp** [ExonomyOrg/exosystems_nuxt#16]
Exosystems needs mailboxes exclusively for the Exonomy app and its community of Exonomists as well as for the Exocracy.com website and its community of Exocrats. The Product Managers and the Evangelists of both projects will monitor incoming mail to their respective mailboxes through pushed notifications.

The definition of done includes a report about how to manage spam since these two email addresses will be published via https://exosystems.net

**Comment by mkzi301** [comment]
### Mailbox Setup and Spam Management

**Steps Taken**:

**1. Accessed Mailcow Admin Interface:**

 - Login to the Mailcow admin interface.

- Navigated to Configuration -> Mail Setup.

**2. Created Mailboxes:**

- Added the following mailboxes:
  - exonomy@exosystems.net
  - Domain: exosystems.net
  - Username: exonomy
  - Password: Set a strong password (noted securely)
  - Name: Exonomy


> exocracy@exosystems.net

Repeated the above steps with username exocracy and name Exocracy

**3.  Configured SOGo Groupware for Monitoring:**

- Logged in to SOGo with credentials for both mailboxes.
- Set up notifications for new emails.
- Configured sharing settings to allow access to relevant Product Managers and Evangelists.

**4. Spam Management Configuration:**

- Configured SpamAssassin settings in Mailcow:
- Set spam score thresholds
- Enabled Bayesian Filtering
- Set up a designated "Spam" folder for users to report missed spam.
- Configured daily spam reports for mailbox review.

**5. Testing and Finalization:**

- Sent test emails to both mailboxes.
- Verified notifications and spam filter functionality.

**Google Doc with Technical Details:**
[ExonomyDoc](https://docs.google.com/document/d/1i1NvgisLeQOAwwgAx8bv-299iGdnv9oq0ur_S7rDa1M/edit?usp=sharing)


_Please review the documentation and let me know if there are any further adjustments needed._
